### ISSUE TITLE
Docker 有考虑增加 linux/arm64/v8 架构支持吗？

### ISSUE THREAD

**Issue by Xheldon** [zmh-program/blob-service#10]
如题，苹果 M 芯片拉取提示：
![CleanShot_2024_11_30_at_19_23_48@2x](https://github.com/user-attachments/assets/f62a5076-20f9-4511-a005-c0fca8926d21)

**Comment by zmh-program** [comment]
後面github workflow新增一下buildx支持，可以先自己build下

**Comment by zmh-program** [comment]
已支持。
