### ISSUE TITLE
Chat Nio 配置自定义文件解析服务报错网络错误的可能情况 - possible errors for configuring the custom file parsing service

### ISSUE THREAD

**Issue by dqzboy** [zmh-program/blob-service#6]
chatnio-blob-service部署完成后，前端访问上传图片正常，但是chatnio的后台配置地址上传图片直接报错，日志也没有看到相关的信息输出
![image](https://github.com/Deeptrain-Community/chatnio-blob-service/assets/42825450/d103176a-a3b9-431e-9e28-8f05afabe857)
![image](https://github.com/Deeptrain-Community/chatnio-blob-service/assets/42825450/285c59a5-d8a4-4aae-b3d5-b7455dbb4184)

chatnio-blob-service使用docker部署
chatnio通过docker部署或者编译部署都提示网络错误

**Comment by zmh-program** [comment]
Please provide your browser logs, the possible factors for this issue are:
1. Mix Content Error: Browser does not allow HTTPS sites to initiate HTTP requests
2. CORS Issue: This is not an issue by default, but if you have misconfigured cross-domain resource sharing, this may cause this issue.

**Comment by dqzboy** [comment]
谢谢，已解决

**Comment by zmh-program** [comment]
marked as pinned issue

**Comment by kitaev-chen** [comment]
> 谢谢，已解决

??? 怎么解决的

**Comment by zmh-program** [comment]
> > 谢谢，已解决
> 
> ??? 怎么解决的

我建议你提供一下你的信息，这样没有任何有用信息呢

**Comment by dqzboy** [comment]
> > 谢谢，已解决
> 
> ??? 怎么解决的

跨域问题，直接配置为公网地址或者nginx代理一下

**Comment by kitaev-chen** [comment]
> > > 谢谢，已解决
> > 
> > 
> > ??? 怎么解决的
> 
> 跨域问题，直接配置为公网地址或者nginx代理一下

谢谢。如果只是想 localhost 的实验下，不知有没有解决方案。我是将 blob service 整合进 searxng 的 compose 文件里，然后设置       - CORS_ALLOW_ORIGINS=* ，结果还是不行。

**Comment by zmh-program** [comment]
F12，看一下请求报错的是什么。

**Comment by kitaev-chen** [comment]
> F12，看一下请求报错的是什么。

多谢提醒，很有帮助。host.docker.internal 之类的问题，其实 compose 里已经改为局域网 ip 重启了，居然是 F5 刷新不行，需要关闭标签再打开。

小文件基本没问题了，9 页的 paper 还是报错：
`400 Client Error: Bad Request for url: http://192.168.xxx:xxx/ocr/predict-by-file`

**Comment by zmh-program** [comment]
这个是paddleocr-api的bug吧。

**Comment by kitaev-chen** [comment]
有可能，不知道能不能把 paddleocr 换成 [zerox](https://github.com/getomni-ai/zerox)

**Comment by zmh-program** [comment]
来提一个新issue，也欢迎来pr。

**Comment by kitaev-chen** [comment]
> 400 Client Error 这个是 paddleocr-api 的 bug 吧。

搞清楚了，我测试的 pdf 抽取 image 之后有各种格式，比如 jpeg， jb2 什么的，前者 paddleocr-api 不支持，后者 blob-service 判断不是图片。难怪各种问题。

**Comment by zmh-program** [comment]
> > 400 Client Error 这个是 paddleocr-api 的 bug 吧。
> 
> 搞清楚了，我测试的 pdf 抽取 image 之后有各种格式，比如 jpeg， jb2 什么的，前者 paddleocr-api 不支持，后者 blob-service 判断不是图片。难怪各种问题。

涨见识了。但是我回去看了一下pdf里抽取image的逻辑，调用`get_images`后没有做判断。
https://github.com/zmh-program/blob-service/blob/main/handlers/pdf.py#L30-L49

至于image哪里做判断了呢，应该是在~/handlers/image.py的process里实现里才有做判断。
https://github.com/zmh-program/blob-service/blob/main/handlers/image.py#L21-L32

**Comment by zmh-program** [comment]
不对不对，你给我绕晕了哈哈哈。
涨见识了。但是我回去看了一下pdf里抽取image的逻辑，调用get_images后没有做判断。
https://github.com/zmh-program/blob-service/blob/main/handlers/pdf.py#L30-L49

至于image哪里做判断了呢，应该是在~/handlers/image.py的process里实现里才有做判断。
https://github.com/zmh-program/blob-service/blob/main/handlers/image.py#L21-L32

涨见识了。但是我回去看了一下pdf里抽取image的逻辑，调用get_images后没有做判断。

https://github.com/zmh-program/blob-service/blob/main/handlers/pdf.py#L30-L49

至于image哪里做判断了呢，应该是在processor.py中的switch实现里才有做判断, process 是没有做判断的。

https://github.com/zmh-program/blob-service/blob/726ad0574edc4e11f1a3ac33507695c165a2a2a1/handlers/processor.py#L57-L62

**Comment by kitaev-chen** [comment]
哦哦，多谢啦！我也是粗略看了一眼，不过加上更全点也挺好的。不知道paddleocr那支持多少，我回头也改改PaddleOCRFastAPI那边看。
